name: check metal

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: macos-26
    steps:
      - name: check metal
        run: |
          xcodebuild -version
          xcrun -f metal
          xcrun metal -v
